### ISSUE TITLE
Unknown error in resolve template

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#1]
http://argo.greekestate.fourigin.com/cms/view/?base=DE&path=about&flush=true

Ich kann den Fehler nicht auflösen ({"statusCode":500,"title":"Error processing request!","message":"No template variations defined in template 'unspecified'!"})

Hast Du eine Idee @ervion ?

**Comment by ervion** [comment]
in der Datei <greekestate-home>/.info stehen alle Nodes mit Template-Referenzen

**Comment by kschaefer76** [comment]
Danke!
Was mich aber noch irritiert hat:

path=home funktioniert, path=about nicht.

Sollte dann Ersteres auch nicht funktionieren, weil beide Nodes ja auf der gleichen Ebene liegen?

**Comment by kschaefer76** [comment]
Ist hier noch was offen?

**Comment by ervion** [comment]
fixed (Link item doesn't have 'alternativ' field
