### ISSUE TITLE
Directory without a page?

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#11]
We have in the "objects" folder the problem, that we did not design a index-page here.
I guess we need it - or find a solution of:

1) Make those folders forwarding to another target
2) Redesign the page, so the "search"-pages move to another folder, but than we loose a clear generation of the breadcrumb on the object-detail-pages

but: 2) will not fix 1)

**Comment by ervion** [comment]
We need an index-page here, a simple overview. Other options brakes the clear concept.
