### ISSUE TITLE
CMS | Process/configuration for dataSourceContent "SITE"

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#12]
We need to define and cofigure:

Options:

- Deliver all pages out of the current one
OR/AND:
- Deliver all pages out of the "index"

Question: Make a difference between page / folder? How?

**Comment by ervion** [comment]
To ignore the current page pass parameter `"IGNORE_OWNER_PAGE" : true` to the DataSource query.

In addition you can specify a regex pattern for matching node names. This pattern should be passed as parameter `"NODE_PATTERN" : "....."`.

With passing of parameter `"NON_RECURSIVE" : true` you prevent recursive resolving of nodes. The result will only contains nodes of the main request level.
