### ISSUE TITLE
Count / size of objects in Thymeleaf

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#13]
Can you implement a function to return the size of object-properties?
Atm I need it to get the amount of hotspots.
As I understood, it is not available ootb.

**Comment by ervion** [comment]
Try to use #lists.size() utility, like here:

https://stackoverflow.com/questions/43484142/how-to-print-array-size-in-thymeleaf

**Comment by kschaefer76** [comment]
Wait!! Only the opener should close a ticket :D
