### ISSUE TITLE
Form-Initialization

### ISSUE THREAD

**Issue by ervion** [Fourigin-GbR/theseus#15]
/forms/init-form

request-body:
{
	"formDefinition": "register-vehicle",
	"customer": "1"
}

response:
{
    "tax.account/stored-account": {
        "DE10 2938 4756 4738 29": "Sparkasse Dresden DE10 2938 4756 4738 29",
        "DE01 2345 6789 0123 45": "Commerzbank DE01 2345 6789 0123 45",
        "DE09 8765 4321 0987 6543 21": "Sparkasse Berlin DE09 8765 4321 0987 6543 21",
        "DE12 3456 7890 1234 5678 90": "Deutsche Bank DE12 3456 7890 1234 5678 90",
        "DE01928374657483": "Dresdner Bank Dresden DE01928374657483"
    },
    "payment.methods/stored-account": {
        "DE10 2938 4756 4738 29": "Sparkasse Dresden DE10 2938 4756 4738 29",
        "DE01 2345 6789 0123 45": "Commerzbank DE01 2345 6789 0123 45",
        "DE09 8765 4321 0987 6543 21": "Sparkasse Berlin DE09 8765 4321 0987 6543 21",
        "DE12 3456 7890 1234 5678 90": "Deutsche Bank DE12 3456 7890 1234 5678 90",
        "DE01928374657483": "Dresdner Bank Dresden DE01928374657483"
    }
}

**Comment by kschaefer76** [comment]
Done and pushed. #1162716dbcb21c5c5a2b7cd08552c1d8eef19935
