### ISSUE TITLE
Forms-Validation before submit

### ISSUE THREAD

**Issue by ervion** [Fourigin-GbR/theseus#18]
At the last step (in case of StepBoxes) in in one-step-forms (e.g. create-customer) the form data should be validated before submitting to the service. We have to send two requests here:
1. /validate (full validation, not a pre-validation!)
2. /register-form in case of no validation errors

Alternatively we have to interpret error messages of /register-form exactly in the same way how we do it for pre-validation. At the moment in case of an validation error we just see an error page without detailed error messages.

**Comment by kschaefer76** [comment]
Done. Please verify.
