### ISSUE TITLE
Forms: edit form data

### ISSUE THREAD

**Issue by ervion** [Fourigin-GbR/theseus#20]
A functionality to edit existing form data should be implemented as an action available from the dashboard. I assume, the user should be redirected to the form with pre-initialized values from the request, that should be changed. 

To implement is the pre-initialization of the form fields (frontend) as well as processing of the new request - updating the data set, re-generating of attachments (backend)

**Comment by kschaefer76** [comment]
Did you try that already to pass that in infos in the first ajax-call, which the from-script is doing to init?

**Comment by ervion** [comment]
I cann't try to pass this infos because I don't have an entryId to retrieve the entry's data. It should be an another request or a variation of the init-request, where you pass not only the customerId but also the entryId of the previouse stored entry.

**Comment by ervion** [comment]
The backend functionality has been implemented. See http://fourigin.com/docuwiki/doku.php?id=products:forms:paths (Initialize form body & Initialize form response) for details.
The new version is already deployed on the dev environment.

**Comment by kschaefer76** [comment]
Why did you choose the property name "active" instead of "selected"?

**Comment by ervion** [comment]
Because we not only have fields like select & check boxes, but also text input fields. The property 'selected' sounds wrong for text fields... 'active' is a little bit better ;)

**Comment by kschaefer76** [comment]
I don't think so. "active" is something for an active status of a process. "selected" is for a passive state.
We have more another problem: We mix things that would have to be differentiated more finely.

I noticed when I implement now the population for an input or textarea: they do not have a "displayname". And an input does not have a status "active" oder "selected".

We should seperate between: 
1) populate the DATA of an form
2) restore the status of opened / closed,... of the form

2) is not part of the current implementation and has to be managed by the form-logic in the client.

What do you think @ervion ?

**Comment by kschaefer76** [comment]
Implemented copied to DEV and pushed.

**Comment by ervion** [comment]
Do you mean something like that:
{
	"enumerations": {
		"tax.account/stored-account": {
			"DE01 2345 6789 0123 45": "DE01 2345 6789 0123 45 (Deutsche Bank Berlin)",
			"DE66 5555 4444 3333 2222 11": "DE66 5555 4444 3333 2222 11 (Deutsche Bank Berlin)",
			"DE11222233334444555566": "DE11 2222 3333 4444 5555 66 (Dresdner Bank Dresden)"
		},
	},
	"values": {
		"handover.options": "office-delivering",
		"tax.account/stored-account": "DE66 5555 4444 3333 2222 11",
		"vehicle-insurance.id": "132435"
	}
}

In this case we will have two parts with values for enumerations (select-fields or dynamic list of radio buttons) with field name and field value, and than a part with just values for pre-population, e.g. from previous form submit?

**Comment by kschaefer76** [comment]
```{
  "userProfile": {
    "vorname": "karsten",
    "telefon": {
      "123456": "12 34 56",
      "0015465": "001 54 65"
    },
    "bankdaten": {
      "a_bank": "A Bank",
      "b_bank": "B Bank",
      "c_bank": "C Bank",
      "d_bank": "D Bank",
      "e_bank": "E Bank"
    }
  },
  "storedData": {
    "vorname": "karsten",
    "telefon": {
      "0015465": "001 54 65"
    }
  }
}
