### ISSUE TITLE
Finalize the website's header & footer

### ISSUE THREAD

**Issue by ervion** [Fourigin-GbR/theseus#23]
Header: phone number
Footer: phone number, links

**Comment by kschaefer76** [comment]
Footer is styled.
Need to be updated: content items and translations.

What type of change you expect for the phone-number in the header?

**Comment by ervion** [comment]
I think, we should write all numbers (phone, mobile, fax) in internatonal format:

Telefon +302741024622

Mobile +306946003222

Fax +302741076506

Why is the footer now soo long? Ist es Absicht? ;)

**Comment by kschaefer76** [comment]
Done.
