### ISSUE TITLE
Unable to resolve token 'index' in path '/regions'

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#5]
When processing this url, the token is not found:

http://argo.greekestate.fourigin.com/cms/view/?base=DE&path=/regions/index&flush=true

**Comment by ervion** [comment]
Es gibt ja auch keinen Knoten mit dem Namen „index“. Dass die entsprechende Seite dann index.html heißen wird, hat nichts mit den Knotennamen zu tun. Richtiger Pfad wäre hier also /regions/athen

**Comment by kschaefer76** [comment]
Das Ticket bezog sich nur beispielhaft auf "index", mit "athen" war es ja auch falsch - ist ja auch gelöst.

Aber es gibt doch den "Pfad" bzw. das Element "index" in jedem Verzeichnis, kann ich es nicht auch automatisch darüber ansprechen, auch wenn es nicht generiert wird?

**Comment by ervion** [comment]
Warum willst du, dass es im Falle eines Verzeichnisses auf die index gegangen wird? Warum auch im CMS? Ist es eine legitime Anforderung? Es soll jetzt kein Gegenargument sein, einfach nur eine kritische Frage.

**Comment by kschaefer76** [comment]
Gute Frage!
Vielleicht weil ich den Prozess von den generierten Seiten dann so kenne, dass ich den eigentlichen "Content"-Namen des ersten Knotens nicht kennen muss.

Wie ist es denn in bpia gelöst?

**Comment by ervion** [comment]
In bpia springt man auf die erste Seite (also index). Wollen wir das hier auch so implementieren?

**Comment by ervion** [comment]
ist (glaube ich) erledigt
