### ISSUE TITLE
Function to get the current page-link

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#6]
Can we have a function who returns the current link to a page for a path?

If it is in CMS, it returns for example:
```
http://argo.greekestate.fourigin.com/cms/view/?base=DE&path=/contact
```

and for production:
```
/kontakt.html
```

**Comment by ervion** [comment]
I‘m working on it already :)

**Comment by ervion** [comment]
p.getPath('/objects/search') // for path relative to the current document root
p.getAbsolutPath('/objects/search') // for absolute path including the domain name
