### ISSUE TITLE
Create documentation for all content items

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#7]
Create a documentation for all content items in the fourigin-wiki.

**Comment by kschaefer76** [comment]
Startet here: http://fourigin.com/docuwiki/doku.php?id=products:cms:content-items

**Comment by ervion** [comment]
done

**Comment by kschaefer76** [comment]
Sehr toll!! :-)

PS: In der liste muss das object auch "list-object" heissen, oder?

**Comment by kschaefer76** [comment]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "alternativ" (class com.fourigin.argo.models.content.elements.LinkElement), not marked as ignorable (8 known properties: "anchorName", "target", "attributes", "title", "name", "typeProperties", "url", "elements"])

**Comment by ervion** [comment]
done
