### ISSUE TITLE
Function to generate id in Thymeleaf

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#8]
Gibt es eine Funktion, die eine ID generiert, die ich in Thymeleaf nutzen kann?
Ansonsten müsstest Du mir eine schreiben. Ich brauche das z.B. um HTML-Elemente eindeutig zuordnen zu können (z.B. für ein Javascript).

**Comment by ervion** [comment]
https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#ids

#ids.seq('name') generiert eine ID mit dem Prefix 'name'

Innerhalb einer Schleife, falls du auf andere benachbarte Elemente zugreifen müsstest, benutzt man #ids.next('name') und #ids.prev('name') entspechend
