### ISSUE TITLE
Storage for "global" content

### ISSUE THREAD

**Issue by kschaefer76** [Fourigin-GbR/theseus#9]
Wo legen wir globalen Inhalt ab?

**Comment by ervion** [comment]
Das Konzept ist, glaube ich, string-replacement-Platzhalter überall in den Content-Items zu definieren, welche in unterem dataSource-Bereich auf andere Dateien referenieren. Zum Teil kann bestehende SiteStructureDataSource benutzt werden (für Daten, die aus anderen "normalen" sichtbaren Seiten kommen sollen). Für Daten, die ausschließlich als globale Daten definiert werden und *nicht* auf den normalen Seiten vorkommen, muss eine neue DataSource geschriebene werden (TBD)
